---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  vars:
    homebrew_taps:
      - m3y/drw
      - tldr-pages/tldr
      - AdoptOpenJDK/openjdk
    homebrew_packages:
      - ansible
      - awscli
      - bash
      - ctags
      - curl
      - drw
      - exa
      - fzf
      - git
      - gnu-sed
      - go
      - gradle
      - httpie
      - jq
      - kubernetes-cli
      - maven
      - mysql
      - nkf
      - openssl
      - { name: openssl, state: linked, install_options: force }
      - readline
      - reattach-to-user-namespace
      - sbt
      - stern
      - thefuck
      - tldr
      - tmux
      - tree
      - vim
      - wget
      - yq
      - zsh
    homebrew_cask_packages:
      - adoptopenjdk8
      - appcleaner
      - docker
      - google-japanese-ime
      - intellij-idea
      - iterm2
      - java
      - karabiner-elements
      - openvpn-connect
      - zoomus

  tasks:
    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: "{{homebrew_taps}}"

    - name: brew パッケージのインストール
      homebrew: >
        name={{ item.name | default(item) }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: "{{homebrew_packages}}"

    - name: brew-cask パッケージのインストール
      homebrew_cask: >
        name={{ item.name | default(item) }}
        state={{ item.state | default('present') }}
      with_items: "{{homebrew_cask_packages}}"
